//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CondicionFisica
    {
        public int CondF_ID { get; set; }
        public Nullable<double> CondF_Peso { get; set; }
        public Nullable<double> Cond_Talla { get; set; }
        public Nullable<double> CondF_IndiceMC { get; set; }
        public Nullable<double> CondF_Temp { get; set; }
        public Nullable<int> CondF_Sistolica { get; set; }
        public Nullable<int> CondF_Diastolica { get; set; }
        public int Exa_ID { get; set; }
    
        public virtual ExamenFisico ExamenFisico { get; set; }
    }
}
