//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioLibrary.Model
{
    using System;
    using System.Collections.Generic;
    using ConsultorioLibrary.CapaDatos.Registro;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Consulta = new HashSet<Consulta>();
            this.Usuario = new HashSet<Usuario>();
            this.Especialidad = new HashSet<Especialidad>();
        }
    
        public int Doc_ID { get; set; }
        public string Doc_Nombre { get; set; }
        public string Doc_Apellido { get; set; }
        public string Doc_Cedula { get; set; }
        public string Doc_Codico { get; set; }
        public string Doc_Telefono { get; set; }
        public string Doc_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> Consulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Especialidad> Especialidad { get; set; }

        internal int Registrar(Doctor objDoctor, ref bool resultadoOk, ref string mensajeError)
        {
            RegistroDoctor registroDoctor = new RegistroDoctor();
            this.Doc_ID = registroDoctor.Registrar(objDoctor, ref resultadoOk, ref mensajeError);
            return this.Doc_ID;
        }
    }
}
