//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Cita = new HashSet<Cita>();
            this.Consulta = new HashSet<Consulta>();
        }
    
        public int Pa_ID { get; set; }
        public string Pa_Nombre { get; set; }
        public string Pa_Apellido { get; set; }
        public string Pa_Cedula { get; set; }
        public Nullable<System.DateTime> Pa_FechaNac { get; set; }
        public Nullable<System.DateTime> Pa_FechaAlta { get; set; }
        public string Pa_Telefono { get; set; }
        public string Pa_Celular { get; set; }
        public string Pa_Email { get; set; }
        public bool Pa_EstaActivo { get; set; }
        public bool Pa_EstaEliminado { get; set; }
        public Nullable<int> Domi_ID { get; set; }
        public Nullable<int> Zo_ID { get; set; }
        public Nullable<int> TP_ID { get; set; }
        public Nullable<int> Est_ID { get; set; }
        public Nullable<int> Gen_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Cita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> Consulta { get; set; }
        public virtual Domicilio Domicilio { get; set; }
        public virtual Estado_Civil Estado_Civil { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Tipo_Paciente Tipo_Paciente { get; set; }
        public virtual Zona Zona { get; set; }
    }
}
